name: Example Workflow

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  ci_step:
    name: Build, tag and push Docker image to DockerHub
    runs-on: ubuntu-latest
      
    steps:
      - 
        name: Check out the source_repo
        uses: actions/checkout@v4
      
      -
        name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/zadanie2
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   

      - 
        name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - 
        name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/zadanie2:cache 
          cache-to: |
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/zadanie2:cache  
          tags: ${{ steps.meta.outputs.tags }}

      - name: Docker Scout CVE Scan
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ steps.meta.outputs.tags }}
          only-severities: critical, high
          summary: true
          exit-code: true

      - name: Conditional Step Execution
        if: steps.docker-scout.outputs.summary == false
        run: |
          echo "No critical or high vulnerabilities detected. Proceeding with GitHub Container Registry login and push."
        
      - name: Login to GitHub Container Registry
        if: steps.docker-scout.outputs.summary == false
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image to GitHub Container Registry
        if: steps.docker-scout.outputs.summary == false
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/maryia03/zadanie2:latest
          cache-from: |
            type=registry,ref=ghcr.io/maryia03/zadanie2:cache 
          cache-to: |
            type=registry,ref=ghcr.io/maryia03/zadanie2:cache
